// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1sBfArxZR5N8L4ZLbRmOcRkCh3Syeb2U',
    appId: '1:57700216320:web:53c06533c39a88d1d1f2e5',
    messagingSenderId: '57700216320',
    projectId: 'universe-app-ifsp',
    authDomain: 'universe-app-ifsp.firebaseapp.com',
    storageBucket: 'universe-app-ifsp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAM4vvXvWZ69PlM6-nZbifNkkiLDaeYN8',
    appId: '1:57700216320:android:71997c3c4ce5bd2ad1f2e5',
    messagingSenderId: '57700216320',
    projectId: 'universe-app-ifsp',
    storageBucket: 'universe-app-ifsp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2l5NJ6CNn92FoFqQTXlT7XoPr-h5hGho',
    appId: '1:57700216320:ios:ce1efdb26d4cf27ad1f2e5',
    messagingSenderId: '57700216320',
    projectId: 'universe-app-ifsp',
    storageBucket: 'universe-app-ifsp.firebasestorage.app',
    iosBundleId: 'br.edu.ifsp.ptb.universeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2l5NJ6CNn92FoFqQTXlT7XoPr-h5hGho',
    appId: '1:57700216320:ios:ce1efdb26d4cf27ad1f2e5',
    messagingSenderId: '57700216320',
    projectId: 'universe-app-ifsp',
    storageBucket: 'universe-app-ifsp.firebasestorage.app',
    iosBundleId: 'br.edu.ifsp.ptb.universeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1sBfArxZR5N8L4ZLbRmOcRkCh3Syeb2U',
    appId: '1:57700216320:web:e212b09f3f1e7024d1f2e5',
    messagingSenderId: '57700216320',
    projectId: 'universe-app-ifsp',
    authDomain: 'universe-app-ifsp.firebaseapp.com',
    storageBucket: 'universe-app-ifsp.firebasestorage.app',
  );
}
